### ISSUE TITLE
Support for dot notation

### ISSUE THREAD

**Issue by dimitarkolev** [bevry/query-engine#31]
Add support for dot notation like in mongo: http://docs.mongodb.org/manual/tutorial/query-documents/#subdocuments

**Comment by balupton** [comment]
Should be handled by the model itself rather than query-engine. See https://github.com/bevry/backbone-nesty specifically https://github.com/bevry/backbone-nesty/blob/2aa8e673f8893e8e0116e2d2686f8715ecc8a4ef/src/lib/backbone-nesty.coffee#L124-L140
